aliases: []
creation_timestamp: 1728368206519
current_stage: None
description: null
last_updated_timestamp: 1728368206519
name: my-classification
run_id: 38ee4f39e8124a6184c2d40169a57b63
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/38ee4f39e8124a6184c2d40169a57b63/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/38ee4f39e8124a6184c2d40169a57b63/artifacts/model
user_id: null
version: 4
