aliases: []
creation_timestamp: 1729505158398
current_stage: None
description: null
last_updated_timestamp: 1729505158398
name: my-classification
run_id: 0051ee84803849e0b130c785f0f4737d
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/0051ee84803849e0b130c785f0f4737d/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/0051ee84803849e0b130c785f0f4737d/artifacts/model
user_id: null
version: 19
