aliases: []
creation_timestamp: 1728147122961
current_stage: None
description: null
last_updated_timestamp: 1728147122961
name: my-regressor
run_id: cb0674ba2dc348cc93545c22ed5a7a79
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/cb0674ba2dc348cc93545c22ed5a7a79/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/cb0674ba2dc348cc93545c22ed5a7a79/artifacts/model
user_id: null
version: 8
