aliases: []
creation_timestamp: 1729948326636
current_stage: None
description: null
last_updated_timestamp: 1729948326636
name: my-classification
run_id: f6d03ea7b25541cbac9116494fe85743
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/f6d03ea7b25541cbac9116494fe85743/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/f6d03ea7b25541cbac9116494fe85743/artifacts/model
user_id: null
version: 35
