aliases: []
creation_timestamp: 1729938781230
current_stage: None
description: null
last_updated_timestamp: 1729938781230
name: my-classification
run_id: 9872fe71bf7846cdba5b2b0802cd67db
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/9872fe71bf7846cdba5b2b0802cd67db/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/9872fe71bf7846cdba5b2b0802cd67db/artifacts/model
user_id: null
version: 30
