artifact_uri: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/3ccd65afbf47432faef21aa142ebcfd5/artifacts
end_time: 1729863485091
entry_point_name: ''
experiment_id: '941905144546297520'
lifecycle_stage: active
run_id: 3ccd65afbf47432faef21aa142ebcfd5
run_name: __default__
run_uuid: 3ccd65afbf47432faef21aa142ebcfd5
source_name: ''
source_type: 4
source_version: ''
start_time: 1729863484980
status: 4
tags: []
user_id: Admin
