artifact_uri: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/2c24a0ab1a7f4e5d9bc68a63e2ca2aeb/artifacts
end_time: 1727265431413
entry_point_name: ''
experiment_id: '941905144546297520'
lifecycle_stage: active
run_id: 2c24a0ab1a7f4e5d9bc68a63e2ca2aeb
run_name: __default__
run_uuid: 2c24a0ab1a7f4e5d9bc68a63e2ca2aeb
source_name: ''
source_type: 4
source_version: ''
start_time: 1727265425589
status: 3
tags: []
user_id: Admin
