aliases: []
creation_timestamp: 1728372166949
current_stage: None
description: null
last_updated_timestamp: 1728372166949
name: my-classification
run_id: 30a01e1a42ff4e9c92577b0c2505d6b2
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/30a01e1a42ff4e9c92577b0c2505d6b2/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/30a01e1a42ff4e9c92577b0c2505d6b2/artifacts/model
user_id: null
version: 6
