aliases: []
creation_timestamp: 1728395236521
current_stage: None
description: null
last_updated_timestamp: 1728395236521
name: my-classification
run_id: 7991d415d1ca41f39aab4ff25507898b
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/7991d415d1ca41f39aab4ff25507898b/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/7991d415d1ca41f39aab4ff25507898b/artifacts/model
user_id: null
version: 12
