aliases: []
creation_timestamp: 1729430511829
current_stage: None
description: null
last_updated_timestamp: 1729430511829
name: my-classification
run_id: 2c09c6058832485e92299571ad99eab9
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/2c09c6058832485e92299571ad99eab9/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/2c09c6058832485e92299571ad99eab9/artifacts/model
user_id: null
version: 16
