aliases: []
creation_timestamp: 1728367683095
current_stage: None
description: null
last_updated_timestamp: 1728367683095
name: my-classification
run_id: 7fb6cbc266134be8a85e7e5f8d3e0927
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/7fb6cbc266134be8a85e7e5f8d3e0927/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/7fb6cbc266134be8a85e7e5f8d3e0927/artifacts/model
user_id: null
version: 1
