aliases: []
creation_timestamp: 1730460524552
current_stage: None
description: null
last_updated_timestamp: 1730460524552
name: my-classification
run_id: 81fd1a67fc1b427eb46a8353cd61336b
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/81fd1a67fc1b427eb46a8353cd61336b/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/81fd1a67fc1b427eb46a8353cd61336b/artifacts/model
user_id: null
version: 36
