aliases: []
creation_timestamp: 1728397853224
current_stage: None
description: null
last_updated_timestamp: 1728397853224
name: my-classification
run_id: f336be7878fa46fab5d275d49ef5872b
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/f336be7878fa46fab5d275d49ef5872b/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/f336be7878fa46fab5d275d49ef5872b/artifacts/model
user_id: null
version: 14
