aliases: []
creation_timestamp: 1729860158523
current_stage: None
description: null
last_updated_timestamp: 1729860158523
name: my-classification
run_id: 5125c72245264ab8a9f9c3f15b287ab4
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/5125c72245264ab8a9f9c3f15b287ab4/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/5125c72245264ab8a9f9c3f15b287ab4/artifacts/model
user_id: null
version: 21
