aliases: []
creation_timestamp: 1729938898341
current_stage: None
description: null
last_updated_timestamp: 1729938898341
name: my-classification
run_id: 72bf6b7b1e0d49e8a464972e7b7aa1ab
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/72bf6b7b1e0d49e8a464972e7b7aa1ab/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/72bf6b7b1e0d49e8a464972e7b7aa1ab/artifacts/model
user_id: null
version: 31
