artifact_uri: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/ecbb1c40b8f84ffca35c3bc75b97d30a/artifacts
end_time: 1729935721145
entry_point_name: ''
experiment_id: '941905144546297520'
lifecycle_stage: active
run_id: ecbb1c40b8f84ffca35c3bc75b97d30a
run_name: data_preprocessing
run_uuid: ecbb1c40b8f84ffca35c3bc75b97d30a
source_name: ''
source_type: 4
source_version: ''
start_time: 1729935719377
status: 3
tags: []
user_id: Admin
