aliases: []
creation_timestamp: 1727266153055
current_stage: None
description: null
last_updated_timestamp: 1727266153055
name: my-regressor
run_id: df4b3fb29ce14b77af08b66f89b03941
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/df4b3fb29ce14b77af08b66f89b03941/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/df4b3fb29ce14b77af08b66f89b03941/artifacts/model
user_id: null
version: 3
