aliases: []
creation_timestamp: 1729938206982
current_stage: None
description: null
last_updated_timestamp: 1729938206982
name: my-classification
run_id: bf41755d799f44d98151cefa04e9ab54
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/bf41755d799f44d98151cefa04e9ab54/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/bf41755d799f44d98151cefa04e9ab54/artifacts/model
user_id: null
version: 29
