aliases: []
creation_timestamp: 1729926655690
current_stage: None
description: null
last_updated_timestamp: 1729926655690
name: my-classification
run_id: 13d6c851641f412faaeff2e5fbbb10d0
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/13d6c851641f412faaeff2e5fbbb10d0/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/13d6c851641f412faaeff2e5fbbb10d0/artifacts/model
user_id: null
version: 24
