aliases: []
creation_timestamp: 1728394978702
current_stage: None
description: null
last_updated_timestamp: 1728394978702
name: my-classification
run_id: 2b102a4432814e81a0e6b4a3459cf86c
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/2b102a4432814e81a0e6b4a3459cf86c/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/2b102a4432814e81a0e6b4a3459cf86c/artifacts/model
user_id: null
version: 11
