aliases: []
creation_timestamp: 1729937222453
current_stage: None
description: null
last_updated_timestamp: 1729937222453
name: my-classification
run_id: 8f91050ed07c41b8bd0b1a49cfcac0d5
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/8f91050ed07c41b8bd0b1a49cfcac0d5/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/8f91050ed07c41b8bd0b1a49cfcac0d5/artifacts/model
user_id: null
version: 28
