artifact_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/0
creation_time: 1727184551192
experiment_id: '0'
last_update_time: 1727184551192
lifecycle_stage: active
name: Default
