aliases: []
creation_timestamp: 1732537647433
current_stage: None
description: null
last_updated_timestamp: 1732537647433
name: my-classification
run_id: adccc318413e4ce2a30033cbfbcda946
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/adccc318413e4ce2a30033cbfbcda946/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/adccc318413e4ce2a30033cbfbcda946/artifacts/model
user_id: null
version: 37
