artifact_uri: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/162708247212727938/f00b4ed18ccd46a2abec0fa9aff7c059/artifacts
end_time: 1727246863717
entry_point_name: ''
experiment_id: '162708247212727938'
lifecycle_stage: active
run_id: f00b4ed18ccd46a2abec0fa9aff7c059
run_name: __default__
run_uuid: f00b4ed18ccd46a2abec0fa9aff7c059
source_name: ''
source_type: 4
source_version: ''
start_time: 1727246858745
status: 3
tags: []
user_id: Admin
