aliases: []
creation_timestamp: 1727267993847
current_stage: None
description: null
last_updated_timestamp: 1727267993847
name: my-regressor
run_id: 6190a77bc54b4c94be8dca0930324ec6
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/6190a77bc54b4c94be8dca0930324ec6/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/6190a77bc54b4c94be8dca0930324ec6/artifacts/model
user_id: null
version: 5
