aliases: []
creation_timestamp: 1728148819544
current_stage: None
description: null
last_updated_timestamp: 1728148819544
name: my-regressor
run_id: 6b808f79659f4604b0cc1df3a4f5a00a
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/6b808f79659f4604b0cc1df3a4f5a00a/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/6b808f79659f4604b0cc1df3a4f5a00a/artifacts/model
user_id: null
version: 9
