aliases: []
creation_timestamp: 1729944715565
current_stage: None
description: null
last_updated_timestamp: 1729944715565
name: my-classification
run_id: 78d5f4b41bc34ffc8aa2065806f861a6
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/78d5f4b41bc34ffc8aa2065806f861a6/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/78d5f4b41bc34ffc8aa2065806f861a6/artifacts/model
user_id: null
version: 34
