aliases: []
creation_timestamp: 1728397549022
current_stage: None
description: null
last_updated_timestamp: 1728397549022
name: my-classification
run_id: cafef3b07889429a8b9f701b390236a4
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/cafef3b07889429a8b9f701b390236a4/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/cafef3b07889429a8b9f701b390236a4/artifacts/model
user_id: null
version: 13
