artifact_uri: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/fabafd2e4fd64ffd89aa24fe3156245f/artifacts
end_time: 1729939533920
entry_point_name: ''
experiment_id: '941905144546297520'
lifecycle_stage: active
run_id: fabafd2e4fd64ffd89aa24fe3156245f
run_name: data_reporting
run_uuid: fabafd2e4fd64ffd89aa24fe3156245f
source_name: ''
source_type: 4
source_version: ''
start_time: 1729939533781
status: 4
tags: []
user_id: Admin
