aliases: []
creation_timestamp: 1729940484889
current_stage: None
description: null
last_updated_timestamp: 1729940484889
name: my-classification
run_id: f3f6bba57d4949b4ad5d32c2ed73d0c4
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/f3f6bba57d4949b4ad5d32c2ed73d0c4/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/f3f6bba57d4949b4ad5d32c2ed73d0c4/artifacts/model
user_id: null
version: 32
