artifact_uri: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/07671aacaa4b4c4d9ffc7d32b482bb0f/artifacts
end_time: 1729947756951
entry_point_name: ''
experiment_id: '941905144546297520'
lifecycle_stage: active
run_id: 07671aacaa4b4c4d9ffc7d32b482bb0f
run_name: __default__
run_uuid: 07671aacaa4b4c4d9ffc7d32b482bb0f
source_name: ''
source_type: 4
source_version: ''
start_time: 1729947751537
status: 4
tags: []
user_id: Admin
