aliases: []
creation_timestamp: 1729852846597
current_stage: None
description: null
last_updated_timestamp: 1729852846597
name: my-classification
run_id: 8adf8538b430482cabe755ab0e54f816
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/8adf8538b430482cabe755ab0e54f816/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/8adf8538b430482cabe755ab0e54f816/artifacts/model
user_id: null
version: 20
