aliases: []
creation_timestamp: 1728394188492
current_stage: None
description: null
last_updated_timestamp: 1728394188492
name: my-classification
run_id: 6756ffec0c0b411cba326ad8dedb0598
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/6756ffec0c0b411cba326ad8dedb0598/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/6756ffec0c0b411cba326ad8dedb0598/artifacts/model
user_id: null
version: 9
