aliases: []
creation_timestamp: 1729436435642
current_stage: None
description: null
last_updated_timestamp: 1729436435642
name: my-classification
run_id: 0205e149f10c4c1d893d32f23fb59ceb
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/0205e149f10c4c1d893d32f23fb59ceb/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/0205e149f10c4c1d893d32f23fb59ceb/artifacts/model
user_id: null
version: 17
