aliases: []
creation_timestamp: 1727265828071
current_stage: None
description: null
last_updated_timestamp: 1727265828071
name: my-regressor
run_id: 098de14816444e4f96268f43fc70666a
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/098de14816444e4f96268f43fc70666a/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/098de14816444e4f96268f43fc70666a/artifacts/model
user_id: null
version: 1
