aliases: []
creation_timestamp: 1729492608740
current_stage: None
description: null
last_updated_timestamp: 1729492608740
name: my-classification
run_id: a6bf5c68f5ed4962a065106b43d5c493
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/a6bf5c68f5ed4962a065106b43d5c493/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/a6bf5c68f5ed4962a065106b43d5c493/artifacts/model
user_id: null
version: 18
