aliases: []
creation_timestamp: 1728398024322
current_stage: None
description: null
last_updated_timestamp: 1728398024322
name: my-classification
run_id: a8adfcc937604d13a6a11afdb473a49f
run_link: null
source: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/a8adfcc937604d13a6a11afdb473a49f/artifacts/model
status: READY
status_message: null
storage_location: file:///C:/Users/Admin/Downloads/AI-839/MLOps/kedro-projects/anant-ai-839/mlflow_runs/941905144546297520/a8adfcc937604d13a6a11afdb473a49f/artifacts/model
user_id: null
version: 15
